import { createProductApplication } from '../src/product-application.js';
import { PRODUCT_SETTING_REGISTRY } from '../src/product-settings.js';
import { CATEGORY_LABELS, recordDescription, renderMemoryCard } from '../src/product-memory.js';
import { exportProductJson } from '../src/product-host-ui.js';
import { PRODUCT_VERSION, PRODUCT_REPOSITORY } from '../src/product-release.js';
import { mountFloatingProduct } from '../src/product-floating.js';
import { esc, button, field, settingsSection, apiSettingsHTML, missingRecommendations, API_INFO } from '../src/product-settings-ui.js';

const ID='shiyi-product-shell';
const NAV=['memory','recording','assistant','api','modules'];

export function initProductShell({documentRef=globalThis.document,host=globalThis,application=null,controller=null,controllerOptions={}}={}){
 if(!documentRef||documentRef.getElementById?.(ID))return null;
 const panel=documentRef.createElement('section');panel.id=ID;panel.className='sy-root';
 panel.innerHTML=`<details class="sy-shell" open><summary class="sy-brand"><span class="sy-mark">拾</span><span>拾忆<small>让故事有迹可循</small></span><span class="sy-version">${PRODUCT_VERSION}</span></summary><div class="sy-body">
 <div class="sy-top"><span data-scope>尚未打开聊天</span><div class="sy-actions">${button('open','开始使用',true)}${button('disable','暂停')}</div></div><p role="status" aria-live="polite" class="sy-status" data-status>连接一个模型，就可以开始整理故事。</p>
 <nav class="sy-nav" aria-label="拾忆导航">${['记忆','记录','助手','API','模块'].map((v,i)=>`<button type="button" data-page="${NAV[i]}" ${i===0?'class="active"':''}>${v}</button>`).join('')}</nav>
 <section data-view="memory"><div class="sy-top"><h3>故事记忆</h3>${button('refresh','刷新')}</div>
 <p class="sy-help">查看已保存的故事细节，或直接补充一件事。</p>
 <details class="sy-card"><summary>记一件事</summary>${field('补充设定或想记住的细节','<textarea rows="3" data-note></textarea>')}${field('谁知道（逗号分隔；未知留空）','<input data-people>')}${button('remember','保存记事',true)}</details>
 <div class="sy-filters"><input data-search aria-label="搜索记忆" placeholder="搜索人物、事件、地点…"><select data-category aria-label="记忆类别"><option value="all">全部类别</option>${Object.entries(CATEGORY_LABELS).filter(([k])=>k!=='awarenessChanges').map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select></div><div data-cards><p class="sy-empty">这里还没有记忆。整理一段聊天，或记一件事。</p></div>
 </section>
 <section data-view="recording" hidden><h3>记录聊天</h3><div class="sy-card"><h4>手动总结</h4>${field('本次总结最近多少楼','<input type="number" min="1" max="200" value="8" data-count>')}<p class="sy-help">最后一楼为 20、填 10，即整理 11–20。</p><details class="sy-advanced"><summary>指定起止楼层</summary><div class="sy-grid">${field('从哪一楼','<input type="number" min="0" data-start placeholder="与聊天 # 编号相同">')}${field('到哪一楼','<input type="number" min="0" data-end placeholder="包含结束楼">')}</div></details>${field('本次想记得更细的内容','<textarea rows="3" data-focus placeholder="留空时沿用长期记录偏好"></textarea>')}<div class="sy-actions">${button('focus-summary','开始总结',true)}${button('stop','停止')}</div></div>${settingsSection('recording')}${button('save-settings','保存记录设置',true)}</section>
 <section data-view="current" hidden><h3>本轮记忆</h3><p class="sy-help">本地预览不发送模型请求。向量与重排仅在启用且实际使用时调用。</p>${field('当前剧情查询','<textarea rows="3" data-query></textarea>')}${button('preview','预览本地召回',true)}<div data-preview></div><h3>最近一次请求准备</h3><div data-actual><p class="sy-empty">尚未向宿主请求加入记忆。</p></div></section>
 <section data-view="assistant" hidden><div class="sy-top"><h3>配置助手</h3><span data-model></span></div><div class="sy-actions"><button type="button" data-jump="api">模型设置</button><button type="button" data-jump="world">添加 TXT / MD / JSON</button></div><div class="sy-actions"><select data-conversation aria-label="历史对话"><option value="main">配置对话</option></select>${button('new-conversation','新对话')}${button('delete-conversation','删除本次对话')}</div><div data-history><p class="sy-empty">说说想怎样记忆，也可以一次说完全部要求。</p></div><div data-proposal></div>${field('你的要求','<textarea rows="4" data-input placeholder="描述你的卡、想保留的细节、希望避免的问题，或让我按导入的规则配置。"></textarea>')}<div class="sy-actions">${button('assistant','发送',true)}${button('beginner','按导入的规则配置')}${button('assistant-stop','停止')}</div><p class="sy-help">Key 不会发送给助手；设置方案应用后才生效。</p></section>
 <section data-view="api" hidden><h3>API 与模型</h3><p class="sy-help">先接通总结模型，其余按需使用。地址与模型均可修改。</p>${apiSettingsHTML()}${button('save-settings','保存 API 设置',true)}</section>
 <section data-view="modules" hidden><h3>模块</h3><div class="sy-module-grid">${[['injection','注入','调整发给 AI 的记忆'],['retrieval','检索','关键词、向量与重排'],['world','世界与知识库','原作、规则文件与别名'],['settings','设置与备份','配置、数据与版本']].map(([key,title,help])=>`<button type="button" data-page="${key}"><strong>${title}</strong><small>${help}</small></button>`).join('')}</div></section>
 <section data-view="injection" hidden><h3>注入</h3>${settingsSection('injection')}${button('save-settings','保存注入设置',true)}<button type="button" data-page="current">查看本轮记忆与召回预览</button></section>
 <section data-view="retrieval" hidden><h3>检索</h3>${settingsSection('retrieval')}<div class="sy-actions">${button('save-settings','保存检索设置',true)}${button('vectors','建立 / 更新向量索引')}</div></section>
 <section data-view="world" hidden><h3>世界与知识库</h3>${settingsSection('world')}${button('save-settings','保存世界设置',true)}<div class="sy-card"><h4>作品与配置文件</h4><p class="sy-help">TXT / MD / JSON 先解析为文字。分析或使用助手时，相关文字会发送给所选模型。</p>${field('文件用途','<select data-purpose><option value="knowledge">原作 / 世界观资料</option><option value="rules">配置 MD / SKILL / JSON 规则</option></select>')}<input type="file" accept=".txt,.md,.json" multiple data-files aria-label="选择资料文件"><div class="sy-actions">${button('import','导入所选文件')}${button('analyze','分段分析资料')}</div><div data-documents></div></div></section>
 <section data-view="settings" hidden><h3>设置与备份</h3><p class="sy-help">配置按当前聊天保存。</p><details class="sy-card" open><summary>数据与备份</summary><div class="sy-actions">${button('export-config','导出纯配置')}${button('export-backup','导出当前聊天备份')}${button('restore-hidden','恢复不再召回的记录')}${button('undo','撤销上次助手配置')}</div><p class="sy-help">纯配置不含记忆、附件、历史或 Key；完整备份包含当前聊天私人内容，请自行保管。</p></details></section><p data-progress class="sy-help"></p></div></details>`;
 const $=s=>panel.querySelector?.(s),$$=s=>[...(panel.querySelectorAll?.(s)??[])];let app=application,snapshot=null,currentPage='memory',paintScope='';
 const modelRequests=new Map();
 function resetModels(kind){modelRequests.get(kind)?.abort();modelRequests.delete(kind);const list=$(`[data-model-list="${kind}"]`);if(list){list.innerHTML='<option value="">先拉取模型列表，也可以在下方直接输入</option>';list.disabled=true;}$(`[data-action="models-${kind}"]`)?.removeAttribute('disabled');if($(`[data-model-status="${kind}"]`))$(`[data-model-status="${kind}"]`).textContent='';}
 function resetAllModels(){for(const kind of Object.keys(API_INFO))resetModels(kind);}
 function syncInherited(){const follow=$('[data-setting="assistantFollowSummary"]')?.checked;if($('[data-api-fields="assistant"]'))$('[data-api-fields="assistant"]').hidden=follow;if($('[data-inherited]')){const model=$('[data-setting="providerModel"]')?.value||'请先设置总结模型';$('[data-inherited]').textContent=follow?`正在沿用：${model}`:'';}}
 function paintCards(){if(!snapshot||!$('[data-cards]'))return;const q=($('[data-search]')?.value??'').trim(),cat=$('[data-category]')?.value??'all';const cards=snapshot.cards.filter(c=>(cat==='all'||cat===c.category)&&recordDescription(c).includes(q));$('[data-cards]').innerHTML=cards.slice(0,100).map(c=>`<article class="sy-card"><span class="sy-tag">${CATEGORY_LABELS[c.category]??'记忆'}</span><p>${esc(recordDescription(c))}</p><details><summary>知情、时间与来源</summary><div class="sy-packet">${esc(renderMemoryCard(c,snapshot.settings))}</div><p class="sy-help">来源：${esc((c.sourceRefs??[]).map(r=>r.sourceId??r).join('、'))}</p></details><button type="button" data-hide="${esc(c.id)}">不再召回</button></article>`).join('')||'<p class="sy-empty">没有符合条件的记忆。</p>';for(const b of $$('[data-hide]'))b.addEventListener('click',()=>run(()=>app.hideRecord(b.getAttribute('data-hide'))));}
 function paint(s){snapshot=s;const scope=JSON.stringify([s.core?.scope,s.stale]);if(scope!==paintScope){paintScope=scope;resetAllModels();}for(const [sel,value]of [['[data-status]',s.message],['[data-scope]',s.enabled?`当前聊天 · ${s.stale?'来源已变化':'已连接'}`:'当前聊天未加载'],['[data-progress]',s.progress],['[data-model]',s.settings.assistantFollowSummary?s.settings.providerModel:s.settings.assistantModel]])if($(sel))$(sel).textContent=value;paintCards();
   for(const f of $$('[data-key]'))if(s.credentialPresent?.[f.getAttribute('data-key')]===false)f.value='';
   if($('[data-history]'))$('[data-history]').innerHTML=s.history.map(m=>`<article class="sy-message ${m.role==='user'?'is-user':''}"><strong>${m.role==='user'?'你':'配置助手'}</strong><div>${esc(m.content)}</div></article>`).join('')||'<p class="sy-empty">描述你的想法，助手会生成可应用的方案。</p>';
   if($('[data-documents]')){$('[data-documents]').innerHTML=s.documents.map(d=>`<div class="sy-document"><strong>${esc(d.name)}</strong><span>${d.purpose==='rules'?'配置规则':'世界资料'} · ${d.chars} 字 · 已分析 ${d.analyzed}/${d.chunks} 段</span><button type="button" data-remove-doc="${esc(d.id)}">删除资料</button></div>`).join('');for(const b of $$('[data-remove-doc]'))b.addEventListener('click',()=>run(async()=>{if(host.confirm?.('删除这份资料？聊天原文不会改变。'))await app.removeDocument(b.getAttribute('data-remove-doc'));}));}
   if($('[data-proposal]')){const p=s.proposal;$('[data-proposal]').innerHTML=p?`<div class="sy-plan"><h4>待应用方案</h4><p>${esc(p.explanation)}</p>${Object.entries(p.patch).map(([k,v])=>`<p><strong>${esc(PRODUCT_SETTING_REGISTRY[k]?.label??k)}</strong><br>${esc(p.before[k])} → ${esc(v)}</p>`).join('')}${button('apply','应用并保存',true)}</div>`:'';$('[data-action="apply"]')?.addEventListener('click',()=>run(async()=>{await app.applyProposal();fill();}));}
   if($('[data-preview]'))$('[data-preview]').innerHTML=s.preview?`<p class="sy-help">预览 · ${s.preview.usedUnits} 估算单位 · ${s.preview.cards.length} 条（非精确 TOKEN 数）</p>${s.preview.degraded?'<p role="status">本轮召回已降级：在线接口失败或向量索引不完整，可能遗漏相关记忆。</p>':''}<div class="sy-packet">${esc(s.preview.text||'没有相关记忆')}</div>`:'';
   if($('[data-actual]'))$('[data-actual]').innerHTML=s.actual?`<p class="sy-help">已加入待发送请求；不代表服务端已接收。${s.actual.usedUnits} 估算单位</p>${s.actual.degraded?'<p role="status">本轮召回已降级，不能视为完整检索结果。</p>':''}<div class="sy-packet">${esc(s.actual.text)}</div>`:'<p class="sy-empty">尚未向宿主请求加入记忆。</p>';
 }
 app??=createProductApplication({host,controller,...controllerOptions,onChange:paint});
 function fill(){resetAllModels();const s=app.state;for(const f of $$('[data-setting]')){const key=f.getAttribute('data-setting');if(f.type==='checkbox')f.checked=Boolean(s.settings[key]);else f.value=s.settings[key]??'';}if($('[data-input]'))$('[data-input]').value=s.draft??'';if($('[data-count]'))$('[data-count]').value=s.settings.messageCount;const select=$('[data-conversation]');if(select){select.innerHTML=s.conversations.map(c=>`<option value="${esc(c.id)}">${esc(c.title)}</option>`).join('')||'<option value="main">配置对话</option>';select.value=s.conversationId;}syncInherited();}
 function collect(root=panel){const patch={};for(const f of root.querySelectorAll('[data-setting]')){const k=f.getAttribute('data-setting'),d=PRODUCT_SETTING_REGISTRY[k];if(['number','integer'].includes(d.type)&&f.value.trim()==='')throw new Error(`${d.label}不能为空`);patch[k]=d.type==='boolean'?f.checked:['number','integer'].includes(d.type)?Number(f.value):f.value;}return patch;}
 function apiPatch(kind,forRequest=false){const patch=collect($(`[data-api-card="${kind}"]`));if(forRequest&&kind==='assistant'&&patch.assistantFollowSummary)Object.assign(patch,collect($('[data-api-card="summary"]')));return patch;}
 async function loadModels(kind){resetModels(kind);const request=new AbortController();modelRequests.set(kind,request);const status=$(`[data-model-status="${kind}"]`),fetchButton=$(`[data-action="models-${kind}"]`);fetchButton.disabled=true;status.textContent='正在拉取…';try{const models=await app.listModels(kind,{patch:apiPatch(kind,true),modelsUrl:$(`[data-models-url="${kind}"]`).value,signal:request.signal});if(modelRequests.get(kind)!==request)return;const select=$(`[data-model-list="${kind}"]`),value=$(`[data-setting="${API_INFO[kind].prefix}Model"]`).value;select.innerHTML='<option value="">请选择模型</option>'+models.map(id=>`<option value="${esc(id)}">${esc(id)}</option>`).join('');select.disabled=!models.length;select.value=models.includes(value)?value:'';status.textContent=models.length?`已获取 ${models.length} 个模型`:'没有可选模型，可直接输入模型名称。';}catch(error){if(modelRequests.get(kind)===request)status.textContent=`拉取未完成：${error.code??error.message}${error.details?.status?`（HTTP ${error.details.status}）`:''}。可以直接输入模型名称。`;}finally{if(modelRequests.get(kind)===request){modelRequests.delete(kind);fetchButton.disabled=false;}}}
 async function run(fn){try{await fn();paint(app.state);}catch(e){if($('[data-status]'))$('[data-status]').textContent=e?.code?`未完成：${e.code}${e.details?.status?`（HTTP ${e.details.status}）`:''}`:String(e.message??'操作未完成');}}
 function summarize(withFocus){const start=$('[data-start]')?.value??'',end=$('[data-end]')?.value??'';if((start==='')!==(end===''))throw new Error('明确范围需要同时填写起点和终点');return app.summarize({count:Number($('[data-count]')?.value??8),...(start!==''?{startIndex:Number(start),endIndex:Number(end)}:{}),focus:withFocus?$('[data-focus]')?.value??'':''});}
 async function download(data,name){const result=await exportProductJson(data,name,{host,documentRef});host.toastr?.success?.(result.mode==='mobile-native'?'已保存到手机 Downloads':'已提交导出');return result;}
 const actions={open:async()=>{await app.open();fill();},disable:()=>app.disable(),refresh:()=>app.refresh(),summarize:()=>summarize(false),'focus-summary':()=>summarize(true),stop:()=>app.stop(),'assistant-stop':()=>app.stop(),remember:async()=>{await app.remember($('[data-note]')?.value??'',$('[data-people]')?.value??'');if($('[data-note]'))$('[data-note]').value='';},preview:()=>app.preview($('[data-query]')?.value??''),'save-settings':()=>app.saveSettings(collect()),'test-summary':()=>app.testConnection('summary'),'test-assistant':()=>app.testConnection('assistant'),'test-embedding':()=>app.testConnection('embedding'),'test-rerank':()=>app.testConnection('rerank'),import:async()=>{for(const f of Array.from($('[data-files]')?.files??[]))await app.addDocument({name:f.name,text:await f.text(),purpose:$('[data-purpose]')?.value});},analyze:()=>app.analyzeDocuments(),assistant:async()=>{await app.assistant($('[data-input]')?.value??'');if($('[data-input]'))$('[data-input]').value='';},beginner:async()=>{await app.analyzeDocuments();await app.assistant('按我导入的配置规则一次性生成完整设置方案，只有必要信息缺失才询问，不需要逐项问卷。');},'new-conversation':async()=>{await app.newConversation();fill();},'delete-conversation':async()=>{if(host.confirm?.('删除当前助手对话？已应用设置和记忆不会删除。')){await app.deleteConversation();fill();}},'restore-hidden':()=>app.restoreHidden(),vectors:()=>app.buildVectors(),undo:async()=>{await app.undoSettings();fill();},'export-config':()=>download(app.exportSettings(),'拾忆-配置.json'),'export-backup':async()=>download(await app.exportBackup(),'拾忆-聊天备份.json')};
 actions['save-settings']=()=>app.saveSettings(collect($(`[data-view="${currentPage}"]`)));
 for(const kind of Object.keys(API_INFO)){
   actions[`save-api-${kind}`]=()=>app.saveSettings(apiPatch(kind));
   actions[`test-${kind}`]=()=>app.testConnection(kind,apiPatch(kind,true));
   actions[`models-${kind}`]=()=>loadModels(kind);
   actions[`recommend-${kind}`]=()=>{const patch=missingRecommendations(apiPatch(kind),kind);for(const [k,v]of Object.entries(patch))$(`[data-setting="${k}"]`).value=v;resetModels(kind);$(`[data-model-status="${kind}"]`).textContent=Object.keys(patch).length?'已补齐，点击保存后生效。':'已有配置保持不变。';};
 }
 for(const [name,fn]of Object.entries(actions))for(const b of $$(`[data-action="${name}"]`))b.addEventListener?.('click',()=>run(fn));
 function setPage(page){if(!$(`[data-view="${page}"]`))return currentPage;currentPage=page;for(const s of $$('[data-view]'))s.hidden=s.getAttribute('data-view')!==page;for(const b of $$('[data-page]'))b.classList?.toggle('active',b.getAttribute('data-page')===page||b.getAttribute('data-page')==='modules'&&!NAV.includes(page));panel.closest?.('.sy-workbench-content')?.scrollTo?.(0,0);return page;}
 for(const b of $$('[data-page]'))b.addEventListener?.('click',()=>setPage(b.getAttribute('data-page')));
 for(const b of $$('[data-jump]'))b.addEventListener?.('click',()=>setPage(b.getAttribute('data-jump')));
 for(const f of $$('[data-key]'))f.addEventListener?.('input',()=>{const kind=f.getAttribute('data-key');app.setKey(kind,f.value);resetModels(kind);if(kind==='summary')resetModels('assistant');});
 for(const [kind,{prefix}]of Object.entries(API_INFO)){
   for(const f of $$(`[data-api-card="${kind}"] [data-setting], [data-models-url="${kind}"]`))f.addEventListener('input',()=>{if(f.getAttribute('data-setting')!==`${prefix}Model`)resetModels(kind);if(kind==='summary')resetModels('assistant');syncInherited();});
   $(`[data-model-list="${kind}"]`)?.addEventListener('change',e=>{if(e.target.value)$(`[data-setting="${prefix}Model"]`).value=e.target.value;syncInherited();});
 }
 $('[data-search]')?.addEventListener?.('input',paintCards);$('[data-category]')?.addEventListener?.('change',paintCards);$('[data-conversation]')?.addEventListener?.('change',()=>run(()=>app.selectConversation($('[data-conversation]').value)));
 let timer;$('[data-input]')?.addEventListener?.('input',()=>{clearTimeout(timer);const value=$('[data-input]').value,context=app.draftContext;timer=setTimeout(()=>run(()=>app.setDraft(value,context)),350);});
 const updates=documentRef.createElement('details');updates.className='sy-card';
 updates.innerHTML=`<summary>版本与更新 · ${PRODUCT_VERSION}</summary><p class="sy-help">从 Git 安装后，在 TT 的扩展管理中检查拾忆更新。更新完成，等待当前任务结束、保存设置后重载页面即可生效，不需要重装 TT。记忆保留，Key 需重新填写。</p><a href="${PRODUCT_REPOSITORY}" target="_blank" rel="noopener noreferrer">安装地址与更新说明</a>`;
 $('[data-view="settings"]')?.appendChild(updates);
 // Populate the real form at mount, before any explicit chat binding or request.
 fill();paint(app.state);
 const floating=mountFloatingProduct({panel,documentRef,host,version:PRODUCT_VERSION});
 return {panel,application:app,controller:controller??app.core,setPage,floating,
   async destroy(){clearTimeout(timer);resetAllModels();floating.destroy();await app.dispose?.();}};
}
